[build]
  publish = "dist"

[build.environment]
  VITE_APP_NAME = "SentinelGo"
  VITE_APP_VERSION = "1.0.0"

[[plugins]]
  package = "netlify-plugin-one"

[[plugins]]
  package = "netlify-plugin-secrets-scanning"

  [plugins.inputs]
    exclude_patterns = ["VITE_*", "import.meta.env.VITE_*"]